/*
 CUSTOMER PURCHASE BEHAVIOR ANALYSIS
 Author: Ayuicy
 Description: Business intelligence queries to understand customer segmentation,
              spending behavior and revenue contribution.
*/


-- Q1. Total revenue generated by gender

SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- Q2. Customers who used a discount and still spent more than average

SELECT 
    customer_id, 
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);


-- Q3. Top 5 products with highest average review rating

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Average purchase amount for Standard vs Express shipping

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Subscriber vs Non-Subscriber spending comparison

SELECT 
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status;


-- Q6. Top 5 products with highest discount usage percentage

SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100,
        2
    ) AS discount_rate_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate_percentage DESC
LIMIT 5;


-- Q7. Customer segmentation by number of previous purchases

WITH customer_segments AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS total_customers
FROM customer_segments
GROUP BY customer_segment;


-- Q8. Top 3 most purchased products in each category

WITH product_ranking AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_orders
FROM product_ranking
WHERE rank_in_category <= 3;


-- Q9. Subscriber status among repeat buyers (more than 5 purchases)

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. Revenue contribution by age group

SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Q10. Revenue contribution by age group
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
